import type { Article } from "../types";
import { demoImages } from "./images";

export const articlesEn: Article[] = [
  {
    id: "anxiety-professional-support",
    locale: "en",
    slug: "when-does-anxiety-deserve-professional-support",
    alternateSlug: "زمان-مراجعه-برای-اضطراب",
    title: "When does anxiety deserve professional support?",
    excerpt: "Anxiety is common — but there are signs worth paying attention to when it starts affecting daily life.",
    category: "anxiety",
    categoryLabel: "Anxiety",
    image: demoImages.blogHero,
    readingMinutes: 5,
    body: [
      { type: "paragraph", text: "Some anxiety is a normal part of life — a deadline, a big decision, an unfamiliar situation. It becomes worth a closer look when it starts to feel constant, or when it begins shaping decisions more than you'd like." },
      { type: "heading", level: 2, text: "Signs it may be time to talk to someone" },
      { type: "list", items: [
        "Worry that feels hard to switch off, even when things are going well",
        "Avoiding situations that didn't used to feel difficult",
        "Physical tension, disrupted sleep, or a racing mind most days",
        "Feeling like anxiety is making decisions for you",
      ] },
      { type: "paragraph", text: "None of these on their own mean something is wrong — they're simply signals worth noticing. A conversation with a therapist can help make sense of what's happening and whether support may help." },
      { type: "heading", level: 2, text: "What support can look like" },
      { type: "paragraph", text: "Therapy for anxiety often focuses on understanding patterns, building a small toolkit of grounding techniques, and slowly widening the space around what feels manageable. It's rarely about eliminating anxiety entirely — more about changing your relationship to it." },
    ],
  },
  {
    id: "repeating-conflicts-relationships",
    locale: "en",
    slug: "why-do-the-same-conflicts-repeat-in-relationships",
    alternateSlug: "چرا-تعارض‌ها-تکرار-می‌شوند",
    title: "Why do the same conflicts repeat in relationships?",
    excerpt: "The same argument, again and again — it's rarely about the dishes. Here's what's often underneath.",
    category: "relationships",
    categoryLabel: "Relationships",
    image: demoImages.couplesOutcomeA,
    readingMinutes: 6,
    body: [
      { type: "paragraph", text: "Most recurring arguments aren't really about the stated topic. Underneath a disagreement about chores or plans, there's often an unmet need — to feel appreciated, heard, or prioritized." },
      { type: "heading", level: 2, text: "A pattern worth noticing" },
      { type: "paragraph", text: "Couples often fall into a cycle: one partner raises a concern, the other feels criticized and withdraws or defends, and the original concern never gets fully addressed. The cycle repeats because the real need underneath was never named." },
      { type: "heading", level: 2, text: "What can help" },
      { type: "list", items: [
        "Naming the feeling underneath the complaint, not just the complaint itself",
        "Slowing down before responding, especially when feeling defensive",
        "Approaching the conversation as two people solving a problem together",
      ] },
      { type: "paragraph", text: "Couples therapy can offer a structured space to interrupt this cycle — not to decide who is right, but to help both people feel understood." },
    ],
  },
  {
    id: "first-therapy-session",
    locale: "en",
    slug: "what-to-expect-from-a-first-therapy-session",
    alternateSlug: "انتظار-از-اولین-جلسه",
    title: "What to expect from a first therapy session",
    excerpt: "Nervous about a first session? Here's a general sense of how it usually goes.",
    category: "getting-started",
    categoryLabel: "Getting Started",
    image: demoImages.individualOutcomeA,
    readingMinutes: 4,
    body: [
      { type: "paragraph", text: "A first session is usually less formal than people expect. It's mostly a conversation — about what brought you in, what you're hoping for, and whether the therapist feels like a good fit." },
      { type: "heading", level: 2, text: "What's usually covered" },
      { type: "list", items: [
        "A little of your background and what led you to reach out",
        "What you'd like to get out of sessions",
        "Practical details — frequency, format, confidentiality",
      ] },
      { type: "quote", text: "There's no obligation to continue after a first session — it's as much about you deciding if it's a good fit as anything else." },
      { type: "paragraph", text: "It's completely normal to feel a little nervous. Most therapists expect that, and the first session is designed to be low-pressure." },
    ],
  },
  {
    id: "setting-boundaries-difficult",
    locale: "en",
    slug: "why-setting-boundaries-can-feel-difficult",
    alternateSlug: "چرا-مرزگذاری-سخت-است",
    title: "Why setting boundaries can feel difficult",
    excerpt: "Saying no shouldn't feel this hard. Here's why it often does — and what can make it easier.",
    category: "boundaries",
    categoryLabel: "Boundaries",
    image: demoImages.homeApproachA,
    readingMinutes: 5,
    body: [
      { type: "paragraph", text: "For many people, setting a boundary brings up guilt long before it brings relief. That reaction often has roots in old patterns — being praised for being agreeable, or learning that conflict felt unsafe." },
      { type: "heading", level: 2, text: "Common reasons boundaries feel hard" },
      { type: "list", items: [
        "Fear of disappointing someone or damaging the relationship",
        "A learned habit of prioritizing others' comfort over your own",
        "Uncertainty about how to say no without a lengthy justification",
      ] },
      { type: "heading", level: 2, text: "A small starting point" },
      { type: "paragraph", text: "Boundaries don't need to be dramatic. A short, clear sentence — without over-explaining — is often enough. Practicing on smaller, lower-stakes situations can make it easier when it matters more." },
    ],
  },
  {
    id: "emotional-burnout-signs",
    locale: "en",
    slug: "signs-of-emotional-burnout-worth-noticing",
    alternateSlug: "نشانه‌های-فرسودگی-هیجانی",
    title: "Signs of emotional burnout worth noticing",
    excerpt: "Burnout isn't always dramatic. It often shows up quietly, over time.",
    category: "burnout",
    categoryLabel: "Burnout",
    image: demoImages.homeApproachB,
    readingMinutes: 5,
    body: [
      { type: "paragraph", text: "Burnout is often described as exhaustion, but it can also show up as numbness, irritability, or a growing sense of detachment from things that used to feel meaningful." },
      { type: "heading", level: 2, text: "Signs worth noticing" },
      { type: "list", items: [
        "Feeling emotionally flat, even about things you usually enjoy",
        "A persistent sense of being 'behind' no matter how much you do",
        "Increased irritability or a shorter fuse than usual",
        "Physical tiredness that doesn't improve much with rest",
      ] },
      { type: "paragraph", text: "Burnout can build slowly, which makes it easy to normalize. Naming it early — and getting support — can make recovery more manageable than waiting until it feels unavoidable." },
    ],
  },
  {
    id: "inner-critic-kindness",
    locale: "en",
    slug: "how-to-respond-more-kindly-to-your-inner-critic",
    alternateSlug: "پاسخ-مهربانانه-به-منتقد-درونی",
    title: "How to respond more kindly to your inner critic",
    excerpt: "That harsh inner voice isn't the truth — it's a pattern. Here's a gentler way to work with it.",
    category: "self-compassion",
    categoryLabel: "Self-Compassion",
    image: demoImages.homeListening,
    readingMinutes: 4,
    body: [
      { type: "paragraph", text: "Most people carry an inner critic — a voice that's quick to point out flaws and slow to acknowledge effort. It can feel like honesty, but it's often just a well-worn habit of thought." },
      { type: "heading", level: 2, text: "A different approach" },
      { type: "list", items: [
        "Notice the tone, not just the content, of self-critical thoughts",
        "Ask what you'd say to a friend in the same situation",
        "Treat self-compassion as a skill to practice, not a personality trait",
      ] },
      { type: "paragraph", text: "This isn't about ignoring mistakes or lowering standards — it's about responding to yourself the way you'd respond to someone you care about." },
    ],
  },
  {
    id: "grounding-techniques-anxiety",
    locale: "en",
    slug: "3-grounding-techniques-for-moments-of-anxiety",
    alternateSlug: "تکنیک‌های-تمرکز-برای-اضطراب",
    title: "3 grounding techniques for moments of anxiety",
    excerpt: "Simple, practical tools that can help bring your attention back to the present moment.",
    category: "coping-tools",
    categoryLabel: "Coping Tools",
    image: demoImages.serviceIndividual,
    readingMinutes: 4,
    body: [
      { type: "paragraph", text: "Grounding techniques are simple exercises that can help interrupt a spiral of anxious thoughts by bringing attention back to the present moment and the body." },
      { type: "heading", level: 2, text: "Three techniques to try" },
      { type: "list", items: [
        "5-4-3-2-1: name five things you can see, four you can touch, three you can hear, two you can smell, one you can taste",
        "Slow breathing: inhale for four counts, hold for four, exhale for six",
        "Feet on the floor: notice the physical sensation of your feet firmly on the ground",
      ] },
      { type: "paragraph", text: "These techniques may help in the moment, but they work best alongside a broader understanding of what's driving the anxiety — which is often where therapy can help." },
    ],
  },
];
